services:
  web:
    build: .
    command: >
      sh -c './wait-for-it.sh db:5432 && uvicorn src.main:app --host 0.0.0.0 --port 8000'
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine
    restart: always
    env_file:
      - .env
