from .config import DB_USER, DB_PASSWORD, DB_NAME, DB_HOST, DB_USER_TEST, DB_PASSWORD_TEST, \
    DB_HOST_TEST, DB_NAME_TEST

DATABASE_URL = f'postgres://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}'
TEST_DATABASE_URL = f'postgres://{DB_USER_TEST}:{DB_PASSWORD_TEST}@{DB_HOST_TEST}/{DB_NAME_TEST}'
